sonar.projectKey=is1-2026-vetcare
sonar.organization=cristhian-chura
sonar.projectName=VetCare IS1-2026
sonar.host.url=https://sonarcloud.io

sonar.sources=src,.github
sonar.tests=test
sonar.test.inclusions=test/**
sonar.exclusions=node_modules/*,coverage/,docs/*
sonar.coverage.exclusions=.github/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info